# Optional Documentation Service
# Run with: docker-compose -f docker-compose.yml -f docker-compose.docs.yml up -d

services:
  # Documentation
  docs:
    build:
      context: ./docs
      dockerfile: Dockerfile
    container_name: Archon-Docs
    ports:
      - "${ARCHON_DOCS_PORT:-3838}:80"
    networks:
      - app-network
    restart: unless-stopped
 
networks:
  app-network:
    name: archon_app-network
    driver: bridge
